### ISSUE TITLE
Salim wants to contribute

### ISSUE THREAD

**Issue by salimcodes** [ChadiDridi/PythonMLPackage#1]
Hey Chadi, 

I am Salim. A student developer from Nigeria. I am a GitHub Campus Expert hence my strong interest in open source. I was wondering if I could contribute to your project. 

I would like to revamp the `ReadMe.md` file. Doing this might make the project more interesting. 

Finally, I found the project on GitHub Education page. How did you get it up there?

**Comment by ChadiDridi** [comment]
Hello Mr Salim, 
You can always contribute and add values to the code or files, feel free to branch an updated version of that file. Already there's I made  new branch for that : 
git fetch origin
git checkout modify-read-me 


the branch is named modify-read-me. 


Feel free to contribute too to any other thing u would like to . that's how open source grows and build a better solutions !

**Comment by ChadiDridi** [comment]
About the 2nd part of the question : github education page. Since I'm still a student, I have access for Education github where students have two options for submission : Learn  or Contribute. Once you're connected to that platform you can submit your chosen repository there and people will see it when they open the platform
